### PR TITLE
Updated agent uml diagram.

### PR DESCRIPTION
**Pull request by fosterlynn**
I am fiddling with the UML diagram in order to try to get my head together to make a lot of progress in our meeting....  do you see any stupid errors in this one? (I know there are some issues not yet resolved here too.)

One specific question: I left the class Relationship, like it is done in activity streams.  To hold the qualified relation together.  Is this OK?

### CODE REVIEW

**Comment by ahdinosaur** [comment]
@fosterlynn looks really great.

minor note: we only subclass Agent into [Person and Group](https://github.com/valueflows/agent/blob/master/context.jsonld#L18-L37), no Organization. i actually prefer that we did it this way, even though it wasn't a conscious decision that i'm aware of.

**Comment by fosterlynn** [comment]
Oh thanks missed that about Organization. Or was it because we didn't have the example yet?  But we do have Organization all over the place in Sensorica and DHEN networks.  And I'm still thinking about Network (essGlobal has that, although it is defined possibly too narrowly for us), as well as the stuff Joshua has been working on.

It might also depend on what existing vocab we decide to use.  I would prefer to not re-invent that wheel, what do you all think?

But I can live with almost any of this, we will just need to subclass for everything else that people use.  Maybe I should start a separate issue about this question....

**Comment by ahdinosaur** [comment]
@fosterlynn let's move this discussion tangent to #51.

**Comment by fosterlynn** [comment]
@ahdinosaur thanks for moving this!

**Comment by fosterlynn** [comment]
Closing will issue PR for a better one.

**Pull request closed without merging**
