### PR TITLE
added relationship *member* with examples

### PR DESCRIPTION
**Pull request by elf-pavlik**
added missing JSON-LD idioms for ObjectProperties

### CODE REVIEW

**Comment by ahdinosaur** [comment]
uhhh... isn't this in conflict with our existing definition of a relationship (a relationship is an object that has `vf:relationshipType`, `vf:subject`, `vf:object`, `vf:context`)? or am i missing something?

**Comment by fosterlynn** [comment]
long story.... see issue #38 .... more discussion needed i'm sure....

but briefly, elf corrected the subject, object, relationship to be @id's, which they are I think; and we added vf:member to the vocab itself, that is where the long story is

**Comment by ahdinosaur** [comment]
i'll need some time to digest #38, so many words, not much time. i'm keen with adding a few "standard" relationships like `member` to our vocab (as per https://github.com/valueflows/agent/issues/26), but i don't want this to mean we add special cases for how we represent relationships (as far as i can tell, this new property `vf:member` introduces a special case), since i feel that goes against our simple abstract model powered by user-defined type objects (in my opinion one of our core design principles).

**Comment by elf-pavlik** [comment]
@ahdinosaur please see diagrams on https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property#proposed-alternative

I will soon propose to delegate all relationships(types) to https://w3id.org/role/

and replace in examples vf:member with role:member

If I don't want to qualify this relationship, I can assert only one triple using direct relationship. vf:member / role:member act as label for the edge in a graph which you can reify (make qualified relation) or just use directly. Both mean the same and we should support both options seamlessly!

**Comment by fosterlynn** [comment]
@elf-pavlik @ahdinosaur Note that the role concept (according to elf's example) is using the split relationship.  For example there is are separate role instances for buyer and seller.

I also think some of the examples in elf's roles are not relationships agreed upon by 2 agents, they are more reflections of economic events - buyer and seller are like this.  So they are indeed roles in one or more events.  Where customer and supplier are more like the agreed upon relationships (or could call them roles).

**Comment by fosterlynn** [comment]
> I will soon propose to delegate all relationships(types) to https://w3id.org/role/

@elf-pavlik looks like we still need to iron out the question of user defined relationships(types).  

@ahdinosaur @elf-pavlik @bhaugen Maybe we should have a call on this?  Can it wait until our next call or should we do it sooner to get this hashed out?

**Comment by ahdinosaur** [comment]
@elf-pavlik i think i understand, but just to make sure, you're saying that [using `member` as a property on the Agent object](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Frawgit.com%2Fvalueflows%2Fagent%2Fmaster%2Fcontext.jsonld%22%2C%7B%22dex%22%3A%22https%3A%2F%2Fholodex.enspiral.com%2Fapi%2F%22%7D%5D%2C%22%40id%22%3A%22dex%3Apeople%2Fmikey%22%2C%22member%22%3A%5B%22dex%3Agroups%2Fenspiral-craftworks%22%5D%7D) is the same as [creating a property object that references the Agent object](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Frawgit.com%2Fvalueflows%2Fagent%2Fmaster%2Fcontext.jsonld%22%2C%7B%22dex%22%3A%22https%3A%2F%2Fholodex.enspiral.com%2Fapi%2F%22%7D%5D%2C%22subject%22%3A%22dex%3Apeople%2Fmikey%22%2C%22relationship%22%3A%22member%22%2C%22object%22%3A%22dex%3Agroups%2Fenspiral-craftworks%22%7D)? as in a proper linked data reasoner would understand these are the same and we're not adding additional non-"standard" sugar for our apps to implement?

**Comment by ahdinosaur** [comment]
> @ahdinosaur @elf-pavlik @bhaugen Maybe we should have a call on this? Can it wait until our next call or should we do it sooner to get this hashed out?

i prefer we wait until the next expected call slot, i'd rather we build up a slow and steady rhythm with our calls than try to rush anything.

**Comment by fosterlynn** [comment]
> i prefer we wait until the next expected call slot, i'd rather we build up a slow and steady rhythm with our calls than try to rush anything.

@ahdinosaur cool

**Comment by elf-pavlik** [comment]
> @elf-pavlik i think i understand, but just to make sure, you're saying that using member as a property on the Agent object is the same as creating a property object that references the Agent object? as in a proper linked data reasoner would understand these are the same and we're not adding additional non-"standard" sugar for our apps to implement?

Example you show uses only subject, relationship (predicate/property), object

``` json
{
  "@context": [
    "https://rawgit.com/valueflows/agent/master/context.jsonld",
    {
      "dex": "https://holodex.enspiral.com/api/"
    }
  ],
  "subject": "dex:people/mikey",
  "relationship": "member",
  "object": "dex:groups/enspiral-craftworks"
}
```

Since it has no additional qualifications for that relationship (I really find term QualifiedRelationship least confusing), we can shortly **state the same** as

``` json
{
  "@context": [
    "https://rawgit.com/valueflows/agent/master/context.jsonld",
    {
      "dex": "https://holodex.enspiral.com/api/"
    }
  ],
  "@id": "dex:people/mikey",
  "member": "dex:groups/enspiral-craftworks"
}
```

**_NOTE**_: [schema:member](http://schema.org/member) has definition as **hasMember**, which I follow in my examples included in this repo. In your example you seem to use it in opposite direction as **isMemberOf**.

If we reverse member to mean **hasMember**, we get

``` json
{
  "@context": [
    "https://rawgit.com/valueflows/agent/master/context.jsonld",
    {
      "dex": "https://holodex.enspiral.com/api/"
    }
  ],
  "subject": "dex:groups/enspiral-craftworks",
  "relationship": "member",
  "object": "dex:people/mikey"
}
```

(just swapping values of subject and object)

and in short

``` json
{
  "@context": [
    "https://rawgit.com/valueflows/agent/master/context.jsonld",
    {
      "dex": "https://holodex.enspiral.com/api/"
    }
  ],
  "@id": "dex:people/mikey",
  "@reverse": {
    "member": "dex:groups/enspiral-craftworks"
  }
}
```

Defining relations/relationships as instances of rdf:Property (label for an edge in directed graph), allows as to use it as property in JSON-LD serialization. Coming back to #21 I see no case where one would use 'agent type' as property name in JSON-LD!

**Comment by ahdinosaur** [comment]
@elf-pavlik thanks for the extended examples. so what connects `rdf:Property` with `as:subject` and `as:object` that an RDF reasoner would know that these different ways of defining relationships are equivalent? i want to make sure we aren't adding more work for ourselves (having to implement multiple cases for how to parse relationship data) just to get some sweet sugar.

**Comment by elf-pavlik** [comment]
Above subject, property, object pattern follows http://www.w3.org/TR/rdf-schema/#ch_reificationvocab

All instances of rdf:Property  (mostly used for labeling edges of directed graph) one can consider _relationship data_, especially ones declared as [owl:ObjectProperty](http://www.w3.org/TR/2012/REC-owl2-primer-20121211/#Entity_Declarations), in JSON-LD using `"@type": "@id"` construct 

I guess we may need to discuss how to **discover** those qualified relations. Having only as starting point `https://holodex.enspiral.com/api/people/mikey` how do you find

``` json
{
  "@context": [
    "https://rawgit.com/valueflows/agent/master/context.jsonld",
    {
      "dex": "https://holodex.enspiral.com/api/"
    }
  ],
  "subject": "dex:people/mikey",
  "relationship": "member",
  "object": "dex:groups/enspiral-craftworks"
}
```

We shouldn't assume, that by dereferencing (making HTTP GET request) to URI which denotes an agent, we will receive included response which includes all the relations(hips) to other agents, resources, events, concepts etc. Dedicated issue for that concern: https://github.com/valueflows/valueflows/issues/59

**Comment by ahdinosaur** [comment]
> Above subject, property, object pattern follows http://www.w3.org/TR/rdf-schema/#ch_reificationvocab

cool, i think i get it now. i appreciate you spending the time to explain this to me. :) although still kinda scared since the OWL document describes itself as being "a very expressive language (both computationally and for users) and thus can be difficult to implement well and to work with", hehe.

**Comment by elf-pavlik** [comment]
> cool, i think i get it now. i appreciate you spending the time to explain this to me. :)

happy to share my current understanding, IMO while we need pieces of code to do their work, we may even more need to build shared understanding wherever possible :)

> although still kinda scared since the OWL document describes itself as being "a very expressive language (both computationally and for users) and thus can be difficult to implement well and to work with", hehe.

I just linked to OWL document to show where I take, from already established and formalized references, terms like **ObjectProperty**, **DataProperty** (shared understanding again!). For now I don't see much need to implementing OWL based reasoning, we may still need to deal with reasoning based on _owl:inverseOf_ based on resolution of https://github.com/valueflows/valueflows/issues/52

So far I've heard that only [rdflib.js](https://github.com/linkeddata/rdflib.js/) (bit old lib, but web pros wrote it back in a days) implements reasoning over _owl:inverseOf_ in JS. While TimBL (one of its contributors and users in projects like [tabulator](http://www.w3.org/2005/ajar/tab)) openly encourages to use single relation definition and than leverage (in|re)verse features of particular syntax `https://github.com/mnot/I-D/issues/39#issuecomment-89789736`

**Pull request merged**
